version: '3'
services:

  dnd-tools-db:
    image: postgres
    env_file: 
      - .env
    environment: 
      POSTGRES_DB: strapi
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
    volumes:
      - ./dnd-tools-local/data:/var/lib/postgresql/data

  dnd-tools-api:
    image: strapi/strapi
    environment: 
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: dnd-tools-db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: dev
      DATABASE_PASSWORD: pass
    volumes:
      - ./dnd-tools-api:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - dnd-tools-db

  dnd-tools-ui:
    build:
      context: ./dnd-tools-ui
      dockerfile: Dockerfile
    volumes:
      - './dnd-tools-ui:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - dnd-tools-api